// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDay():Promise<string>;

export function GetPresentations():Promise<Array<main.Presentation>>;

export function GetSession():Promise<main.Session>;

export function GetSessions(arg1:string):Promise<Array<main.Session>>;

export function OpenFiles():Promise<void>;

export function OpenMyPC():Promise<void>;

export function RoomList():Promise<Array<main.Room>>;

export function StartPresentation():Promise<void>;
