// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPresentations(arg1) {
  return window['go']['main']['App']['GetPresentations'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function OpenFiles() {
  return window['go']['main']['App']['OpenFiles']();
}

export function OpenMyPC() {
  return window['go']['main']['App']['OpenMyPC']();
}

export function RoomList() {
  return window['go']['main']['App']['RoomList']();
}

export function StartPresentation() {
  return window['go']['main']['App']['StartPresentation']();
}
