// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FileSyncStatus(arg1:main.Room):Promise<void>;

export function GetPresentations(arg1:number):Promise<Array<main.Presentation>>;

export function GetSession(arg1:number):Promise<main.Session>;

export function GetSessions(arg1:string):Promise<Array<main.Session>>;

export function OpenFiles():Promise<void>;

export function OpenMyPC():Promise<void>;

export function RefreshFileList(arg1:number):Promise<Array<main.File>>;

export function RoomList():Promise<Array<main.Room>>;

export function SetRoom(arg1:string):Promise<main.Session>;

export function StartPresentation():Promise<void>;

export function SyncFiles(arg1:main.Room):Promise<void>;
