// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSessionData() {
  return window['go']['main']['App']['GetSessionData']();
}

export function OpenFiles() {
  return window['go']['main']['App']['OpenFiles']();
}

export function StartPresentation() {
  return window['go']['main']['App']['StartPresentation']();
}
