// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSessionData():Promise<Array<main.Presentation>>;

export function OpenFiles():Promise<string>;

export function StartPresentation():Promise<void>;
